# Generated by Django 2.2 on 2019-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
